export enum Letter {
    KAGYI = "က",
    KHAGWE = "ခ",
    // GANGE = "ဂ",
    // GHAGYI = "ဃ",
    // NGA = "င",
    // SALONE = "စ",
    // SALEIN = "ဆ",
    // ZAGWE = "ဇ",
    // ZAMYINZWE = "ဈ",
    // NYA = "ည",
    // NNYA = "ဉ",
    // TTA = "ဋ",
    // TTHA = "ဌ",
    // DDA = "ဍ",
    // DDHA = "ဎ",
    // NNA = "ဏ",
    // TA = "တ",
    // THA = "ထ",
    // DA = "ဒ",
    // DHA = "ဓ",
    // NA = "န",
    // PA = "ပ",
    // PHA = "ဖ",
    // BA = "ဗ",
    // BHA = "ဘ",
    // MA = "မ",
    // YA = "ယ",
    // RA = "ရ",
    // LA = "လ",
    // WA = "ဝ",
    // SA = "သ",
    // HA = "ဟ",
    // LLA = "ဠ",
    // A = "အ",
    // I = "ဣ",
    // II = "ဤ",
    // U = "ဥ",
    // UU = "ဦ",
    // E = "ဧ",
    // O = "ဩ",
    // AU = "ဪ",
    // ANUSVARA = "ံ",
    // VISARGA = "း",
    // VIRAMA = "်",
    // ASAT = "္",
    // MEDIAL_YA = "ျ",
    // MEDIAL_RA = "ြ",
    // MEDIAL_WA = "ွ",
    // MEDIAL_HA = "ှ",
    // GREAT_SA = "ဿ",
}

import Svg from 'react-native-svg';

/// number | string refers to the module id of the svg file
export const LetterSvgs: Record<Letter, number | string> = {
    [Letter.KAGYI]: require('@/assets/chars/က.svg'),
    [Letter.KHAGWE]: require('@/assets/chars/ခ.svg'),
    // [Letter.GANGE]: require('@/assets/chars/ဂ.svg'),
    // [Letter.GHAGYI]: require('@/assets/chars/ဃ.svg'),
    // [Letter.NGA]: require('@/assets/chars/င.svg'),
    // [Letter.SALONE]: require('@/assets/chars/စ.svg'),
}

