export enum Letter {
    KAGYI = "က",
    KHAGWE = "ခ",
    GANGE = "ဂ",
    GHAGYI = "ဃ",
    NGA = "င",
    SALONE = "စ",
    SALEIN = "ဆ",
    ZAGWE = "ဇ",
    ZAMYINZWE = "ဈ",
    NYA = "ည",
    NNYA = "ဉ",
    TTA = "ဋ",
    TTHA = "ဌ",
    DDA = "ဍ",
    DDHA = "ဎ",
    NNA = "ဏ",
    TA = "တ",
    THA = "ထ",
    DA = "ဒ",
    DHA = "ဓ",
    NA = "န",
    PA = "ပ",
    PHA = "ဖ",
    BA = "ဗ",
    BHA = "ဘ",
    MA = "မ",
    YA = "ယ",
    RA = "ရ",
    LA = "လ",
    WA = "ဝ",
    SA = "သ",
    HA = "ဟ",
    LLA = "ဠ",
    A = "အ",


    II = "ဤ",
    U = "ဥ",
    E = "ဧ",
    GREAT_SA = "ဿ",

    // ANUSVARA = "ံ",
    // VISARGA = "း",
    // VIRAMA = "်",
    // ASAT = "္",
    // MEDIAL_YA = "ျ",
    // MEDIAL_RA = "ြ",
    // MEDIAL_WA = "ွ",
    // MEDIAL_HA = "ှ",
}