export enum Letter {
    KAGYI = "က",
    KHAGWE = "ခ",
    GANGE = "ဂ",
    GHAGYI = "ဃ",
    NGA = "င",
    SALONE = "စ",
    SALEIN = "ဆ",
    ZAGWE = "ဇ",
    ZAMYINZWE = "ဈ",
    NYA = "ည",
    NNYA = "ဉ",
    TTA = "ဋ",
    TTHA = "ဌ",
    DDA = "ဍ",
    DDHA = "ဎ",
    NNA = "ဏ",
    TA = "တ",
    THA = "ထ",
    DA = "ဒ",
    DHA = "ဓ",
    NA = "န",
    PA = "ပ",
    PHA = "ဖ",
    BA = "ဗ",
    BHA = "ဘ",
    MA = "မ",
    YA = "ယ",
    RA = "ရ",
    LA = "လ",
    WA = "ဝ",
    SA = "သ",
    HA = "ဟ",
    LLA = "ဠ",
    A = "အ",
    // I = "ဣ",
    // II = "ဤ",
    // U = "ဥ",
    // UU = "ဦ",
    // E = "ဧ",
    // O = "ဩ",
    // AU = "ဪ",
    // ANUSVARA = "ံ",
    // VISARGA = "း",
    // VIRAMA = "်",
    // ASAT = "္",
    // MEDIAL_YA = "ျ",
    // MEDIAL_RA = "ြ",
    // MEDIAL_WA = "ွ",
    // MEDIAL_HA = "ှ",
    // GREAT_SA = "ဿ",
}

import Svg from 'react-native-svg';

/// number | string refers to the module id of the svg file
export const LetterSvgs: Record<Letter, number | string> = {
    [Letter.KAGYI]: require('@/assets/chars/kagyi.svg'),
    [Letter.KHAGWE]: require('@/assets/chars/khagwe.svg'),
    [Letter.GANGE]: require('@/assets/chars/gange.svg'),
    [Letter.GHAGYI]: require('@/assets/chars/ghagyi.svg'),
    [Letter.NGA]: require('@/assets/chars/nga.svg'),
    [Letter.SALONE]: require('@/assets/chars/salone.svg'),
    [Letter.SALEIN]: require('@/assets/chars/salein.svg'),
    [Letter.ZAGWE]: require('@/assets/chars/zagwe.svg'),
    [Letter.ZAMYINZWE]: require('@/assets/chars/zamyinzwe.svg'),
    [Letter.NYA]: require('@/assets/chars/nya.svg'),
    [Letter.NNYA]: require('@/assets/chars/nnya.svg'),
    [Letter.TTA]: require('@/assets/chars/tta.svg'),
    [Letter.TTHA]: require('@/assets/chars/ttha.svg'),
    [Letter.DDA]: require('@/assets/chars/dda.svg'),
    [Letter.DDHA]: require('@/assets/chars/ddha.svg'),
    [Letter.NNA]: require('@/assets/chars/nna.svg'),
    [Letter.TA]: require('@/assets/chars/ta.svg'),
    [Letter.THA]: require('@/assets/chars/tha.svg'),
    [Letter.DA]: require('@/assets/chars/da.svg'),
    [Letter.DHA]: require('@/assets/chars/dha.svg'),
    [Letter.NA]: require('@/assets/chars/na.svg'),
    [Letter.PA]: require('@/assets/chars/pa.svg'),
    [Letter.PHA]: require('@/assets/chars/pha.svg'),
    [Letter.BA]: require('@/assets/chars/ba.svg'),
    [Letter.BHA]: require('@/assets/chars/bha.svg'),
    [Letter.MA]: require('@/assets/chars/ma.svg'),
    [Letter.YA]: require('@/assets/chars/ya.svg'),
    [Letter.RA]: require('@/assets/chars/ra.svg'),
    [Letter.LA]: require('@/assets/chars/la.svg'),
    [Letter.WA]: require('@/assets/chars/wa.svg'),
    [Letter.SA]: require('@/assets/chars/sa.svg'),
    [Letter.HA]: require('@/assets/chars/ha.svg'),
    [Letter.LLA]: require('@/assets/chars/lla.svg'),
    [Letter.A]: require('@/assets/chars/a.svg'),


    // [Letter.GANGE]: require('@/assets/chars/ဂ.svg'),
    // [Letter.GHAGYI]: require('@/assets/chars/ဃ.svg'),
    // [Letter.NGA]: require('@/assets/chars/င.svg'),
    // [Letter.SALONE]: require('@/assets/chars/စ.svg'),
}

